name: Deployment

on:
  push:
    branches: [terraform-deploy]

jobs:
  deployTerraform:
    name: Deploy AWS Infrastructure via Terraform
    # needs: flake8
    runs-on: ubuntu-latest
    outputs:
      SERVER_PUBLIC_IP: ${{ steps.set-ip.outputs.instance_public_ip}}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: us-east-1
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform init
        id: init
        run: |
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve
        working-directory: terraform
      - name: Set output
        id: set-ip
        run: |-
          echo "instance_public_ip=$(terraform output --raw instance_public_ip)" >> $GITHUB_OUTPUT
        working-directory: terraform
  
  deployModel:
    name: Access server
    on: push
    jobs:
      access_server:
        name: Access server
        runs-on: ubuntu-latest
        steps:
          - name: Create a file
            uses: appleboy/ssh-action@master
            with:
              host: ${{ needs.deployTerraform.outputs.SERVER_PUBLIC_IP }}
              username: ubuntu
              key: ${{ secrets.PRIVATE_KEY }}
              script: echo hello world > hello.txt